### ISSUE TITLE
client language support for Java

### ISSUE THREAD

**Issue by Ballhausen** [fdrtd/fdrtd#8]

**Comment by UNakade** [comment]
In JAVA, there's no equivalent to the Python `__getattr__` or `**kwargs`. All methods need to be defined along with their input types before the classes are compiled. Even if we decide to dynamically generate the required classes (one for each Microservice) after we get a list of publicly accessible functions from the fdrtd server, the JAVA client will need to know the names and default values of all inputs to every function. Also, if there's a function that can be called in two different ways, say f(a) or f(a, b), we need to define two separate functions with those signatures. Imagine all the possible permutations and combinations when your function has 10 inputs. 
I think it's really difficult to write a JAVA client which is similar to the Python one we have right now. The simplification afforded by the Representation class might be impossible in JAVA. In my opinion, it would be simpler to write a single function `representation_object.call(String function_name, ObjectArray args, Dictionary kwargs)`.
